version: "3"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always

  mongo:
    image: mongo:3.6

  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/test
      - PORT=8080
    links:
      - mongo
    depends_on:
      - mongo
      - nginx
    volumes:
      - .:/starter
      - /starter/node_modules
